version: '3.7'

services:
    main-prod:
        image: main-prod
        build: 
            context: .
            target: prod
        command: npm run start:prod
        ports:
            - 80:3001
        env_file:
            - .env
        restart: unless-stopped